dist: xenial
language: ruby

services:
  - docker

branches:
  only:
    - qa
    - production
    - myAccount-qa-feature

jobs:
  include:
    - stage: docker build
      if: (branch = qa or branch = production or branch = myAccount-qa-feature)
      before_install:
        - if [[ $TRAVIS_BRANCH == "myAccount-qa-feature" ]];
          then
          export NEXT_PUBLIC_APP_ENV="qa";
          fi
        - if [[ "$TRAVIS_BRANCH" == "production" ]];
          then
          export NEXT_PUBLIC_APP_ENV="production";
          fi
      env:
        - ECR_URL=946183545209.dkr.ecr.us-east-1.amazonaws.com/research-catalog
        - AWS_DEFAULT_REGION=us-east-1
        - AWS_REGION=us-east-1
      install:
        - pip install --user awscli
        - export LOCAL_TAG_NAME="myaccount-qa-feature-latest"
      script:
        - eval $(aws ecr get-login --no-include-email --region us-east-1)
        - docker build -t "$LOCAL_TAG_NAME" --build-arg NEXT_PUBLIC_APP_ENV="${NEXT_PUBLIC_APP_ENV}" .
        - docker tag "$LOCAL_TAG_NAME" "$ECR_URL:$LOCAL_TAG_NAME"
        # Re-tag last latest image just in case
        - |
          MANIFEST=$(aws ecr batch-get-image --repository-name research-catalog --image-ids imageTag="$NEXT_PUBLIC_APP_ENV-latest" --output json | jq --raw-output --join-output '.images[0].imageManifest')
          aws ecr batch-delete-image --repository-name research-catalog --image-ids imageTag="$NEXT_PUBLIC_APP_ENV-previous" || true
          aws ecr put-image --repository-name research-catalog --image-tag "$NEXT_PUBLIC_APP_ENV-previous" --image-manifest "$MANIFEST" || true
        - docker push "$ECR_URL:$LOCAL_TAG_NAME"

    - stage: deploy myAccount-qa-feature
      if: branch IN (myAccount-qa-feature) AND type != pull_request
      env:
        - AWS_DEFAULT_REGION=us-east-1
        - AWS_REGION=us-east-1
        - CLUSTER_NAME=research-catalog-qa
      install:
        - pip install --user awscli
      script:
        - aws ecs update-service --cluster $CLUSTER_NAME --service $CLUSTER_NAME --force-new-deployment

    - stage: deploy production
      if: branch IN (production) AND type != pull_request
      env:
        - AWS_DEFAULT_REGION=us-east-1
        - AWS_REGION=us-east-1
        - CLUSTER_NAME=research-catalog-production
      install:
        - pip install --user awscli
      script:
        - aws ecs update-service --cluster $CLUSTER_NAME --service $CLUSTER_NAME --force-new-deployment
