version: "3"

services:
  app:
    image: research-catalog
    build:
      context: .
      args:
        - NODE_ENV=local
      dockerfile: Dockerfile.development
    ports:
      - 8080:8080
    volumes:
      - ./pages:/app/pages
      - ./styles:/app/styles
