import type { IconNames } from "@nypl/design-system-react-components"
import type {
  Patron,
  PatronUpdateBody,
  SierraPatron,
} from "../../../types/myAccountTypes"

import { buildPatron } from "../../../utils/myAccountUtils"
import { filteredPickupLocations } from "../../../utils/myAccountUtils"

type Phone = { number: string; type: string }
type PhoneOrEmail = string | Phone

export const getLibraryByCode = (code) =>
  filteredPickupLocations.find((loc) => loc.code.trim() === code.trim())

export const accountSettings = [
  {
    field: "phones",
    icon: "communicationCall",
    term: "Phone",
    description: (value: Phone[]) => value[0]?.number,
  },
  {
    field: "emails",
    icon: "communicationEmail",
    term: "Email",
    description: (value: string[]) => value[0],
  },
  {
    field: "notificationPreference",
    icon: "communicationChatBubble",
    term: "Notification preference",
  },
  {
    field: "homeLibrary",
    icon: "actionHome",
    term: "Home library",
    description: (location) => {
      console.log(location)
      return location?.name
    },
  },
  {
    field: "pin",
    icon: "actionLockClosed",
    term: "Pin/Password",
    description: (_) => "****",
  },
] as {
  field: string
  icon: IconNames
  term: string
  description?: (any) => string
}[]

export const updatePhoneOrEmailArrayWithNewPrimary = (
  newPrimary: PhoneOrEmail,
  currentValues: PhoneOrEmail[]
) => {
  const removedNewPrimaryIfPresent = currentValues.filter((val) => {
    if (val["type"]) return val["number"] !== newPrimary["number"]
    return val !== newPrimary
  })
  return [newPrimary, ...removedNewPrimaryIfPresent]
}

/** Parses the account settings form submission event target and turns it into
 * the payload for the patron settings update request.
 */
export const parseAccountSettingsPayload = (
  formSubmissionBody,
  settingsData: Patron
) => {
  return accountSettings.reduce((putRequestPayload, setting) => {
    const field = setting.field
    const fieldValue = formSubmissionBody[field]?.value
    if (!fieldValue) {
      return putRequestPayload
    }
    switch (field) {
      case "pin":
        // pin is handled in a separate dialog
        break
      case "emails":
        putRequestPayload["emails"] = updatePhoneOrEmailArrayWithNewPrimary(
          fieldValue,
          settingsData.emails
        ) as string[]
        break
      // TODO: right now we are assuming that all phones are mobile phones.
      // follow on ticket outlines two different inputs
      case "phones":
        putRequestPayload["phones"] = updatePhoneOrEmailArrayWithNewPrimary(
          { number: fieldValue, type: "t" },
          settingsData.phones
        ) as Phone[]
        break
      case "notificationPreference":
        putRequestPayload["fixedFields"] = {
          "268": {
            label: "Notice Preference",
            value: fieldValue,
          },
        }
        break
      case "homeLibrary":
        putRequestPayload.homeLibraryCode = fieldValue.split("@")[0]
    }
    return putRequestPayload
  }, {} as PatronUpdateBody)
}

export const addHomeLibraryObjectToPayload = (homeLibraryTuple, payload) => {
  if (homeLibraryTuple) {
    const homeLibrary = { code: homeLibraryTuple[0], name: homeLibraryTuple[1] }
    payload.homeLibrary = homeLibrary
  }
  return payload
}

// Combines original patron state with the payload generated by parseAccountSettingsPayload
// so the account settings display can update without a data refresh.
export const buildUpdatedPatronDisplayData = (
  originalPatronData: Patron,
  patronUpdateBody: SierraPatron,
  homeLibrary?: string
) => {
  const newData = buildPatron(patronUpdateBody)
  Object.keys(originalPatronData).forEach((setting) => {
    if (!newData[setting] || !newData[setting].length) {
      newData[setting] = originalPatronData[setting]
    }
  })
  if (homeLibrary) {
    newData.homeLibrary = {
      code: homeLibrary.split("@")[0],
      name: homeLibrary.split("@")[1],
    }
  }
  return newData
}
