// generated by loadSearchVocabs()
    export const searchVocabularies = {
  "formats": [
    {
      "value": "3",
      "label": "E-video"
    },
    {
      "value": "4",
      "label": "Tablet"
    },
    {
      "value": "5",
      "label": "Read-along book"
    },
    {
      "value": "7",
      "label": "Teacher audio"
    },
    {
      "value": "-",
      "label": "Miscellaneous"
    },
    {
      "value": "a",
      "label": "Book/text"
    },
    {
      "value": "b",
      "label": "Blu-ray"
    },
    {
      "value": "c",
      "label": "Notated music"
    },
    {
      "value": "d",
      "label": "Manuscript notated music"
    },
    {
      "value": "e",
      "label": "Map"
    },
    {
      "value": "g",
      "label": "Film, slide, etc."
    },
    {
      "value": "h",
      "label": "Microform"
    },
    {
      "value": "i",
      "label": "Spoken word recording"
    },
    {
      "value": "j",
      "label": "Musical recording"
    },
    {
      "value": "k",
      "label": "Picture"
    },
    {
      "value": "l",
      "label": "Large print"
    },
    {
      "value": "m",
      "label": "Computer file"
    },
    {
      "value": "n",
      "label": "E-audiobook"
    },
    {
      "value": "o",
      "label": "Kit"
    },
    {
      "value": "p",
      "label": "Archival mix"
    },
    {
      "value": "r",
      "label": "3-D object"
    },
    {
      "value": "s",
      "label": "VHS"
    },
    {
      "value": "t",
      "label": "Manuscript"
    },
    {
      "value": "u",
      "label": "Audiobook"
    },
    {
      "value": "v",
      "label": "DVD"
    },
    {
      "value": "w",
      "label": "Web resource"
    },
    {
      "value": "y",
      "label": "Music CD"
    },
    {
      "value": "z",
      "label": "E-book"
    }
  ],
  "collections": [
    {
      "value": "bur",
      "label": "Yoseloff Business Center",
      "holdingLocations": [
        "bur51"
      ]
    },
    {
      "value": "mab",
      "label": "Art & Architecture Collection",
      "holdingLocations": [
        "mab01",
        "mab0v",
        "mab82",
        "mab88",
        "mab89",
        "mab92",
        "mab98",
        "mab99",
        "mabb1",
        "mabb2",
        "mabb3",
        "mabm2",
        "rcmb2",
        "rcmb8",
        "rcmb9"
      ]
    },
    {
      "value": "mac",
      "label": "Arents Collection",
      "holdingLocations": [
        "mac82",
        "macc2"
      ]
    },
    {
      "value": "mae",
      "label": "Berg Collection",
      "holdingLocations": [
        "mae82",
        "mae92",
        "maee2"
      ]
    },
    {
      "value": "maf",
      "label": "Dorot Jewish Division",
      "holdingLocations": [
        "maf32",
        "maf82",
        "maf88",
        "maf92",
        "maf98",
        "maf99",
        "maff1",
        "maff3",
        "rcmf2",
        "rcmf8",
        "rcmf9"
      ]
    },
    {
      "value": "mag",
      "label": "Milstein Division",
      "holdingLocations": [
        "mag82",
        "mag92",
        "mag98",
        "magg1",
        "magg2",
        "rcmg2",
        "rcmg8",
        "rcmg9",
        "magg3"
      ]
    },
    {
      "value": "mak",
      "label": "DeWitt Wallace Periodical Room",
      "holdingLocations": [
        "mak32",
        "mak82",
        "makk3"
      ]
    },
    {
      "value": "mal",
      "label": "General Research Division",
      "holdingLocations": [
        "mai32",
        "mai82",
        "mai92",
        "mal17",
        "mal23",
        "mal42",
        "mal72",
        "mal82",
        "mal92",
        "mala",
        "mala1",
        "malc",
        "mall1",
        "malm2",
        "maln",
        "maln1",
        "malv2",
        "malw",
        "malw1",
        "rc2ma",
        "rc2mj",
        "rcma2",
        "rcmi2",
        "rcmj2",
        "rcml2",
        "rcml8"
      ]
    },
    {
      "value": "mao",
      "label": "Manuscripts and Archives Division",
      "holdingLocations": [
        "mao82",
        "mao92",
        "maor2",
        "rcmo2"
      ]
    },
    {
      "value": "map",
      "label": "Lionel Pincus and Princess Firyal Map Division",
      "holdingLocations": [
        "map08",
        "map32",
        "map42",
        "map82",
        "map92",
        "map98",
        "map99",
        "mapp1",
        "mapp2",
        "mapp3",
        "mapp8",
        "mapp9",
        "rcmp2",
        "rcmp8",
        "rcmp9"
      ]
    },
    {
      "value": "maq",
      "label": "Pforzheimer Collection",
      "holdingLocations": [
        "maqq2",
        "rcmq2"
      ]
    },
    {
      "value": "mar",
      "label": "Rare Book Division",
      "holdingLocations": [
        "mar82",
        "mar92",
        "mard2",
        "marr2",
        "rcmr2"
      ]
    },
    {
      "value": "mas",
      "label": "Photography Collection",
      "holdingLocations": [
        "mas82",
        "mas92",
        "masb2",
        "mass2",
        "masu2",
        "rcms2"
      ]
    },
    {
      "value": "mau",
      "label": "Print Collection",
      "holdingLocations": [
        "mauu1",
        "mauu2"
      ]
    },
    {
      "value": "pad",
      "label": "Dance Division",
      "holdingLocations": [
        "pad11",
        "pad22",
        "pad28",
        "pad32",
        "pad38",
        "pad42",
        "rcpd2",
        "rcpd8",
        "rcpd9"
      ]
    },
    {
      "value": "paf",
      "label": "Theatre on Film and Tape Archive",
      "holdingLocations": [
        "paf28",
        "paf29",
        "rcpf2",
        "rcpf8",
        "rcpf9"
      ]
    },
    {
      "value": "pah",
      "label": "Archives of Recorded Sound",
      "holdingLocations": [
        "pah11",
        "pah22",
        "pah32",
        "pah38",
        "pah42",
        "rcph2",
        "rcph8",
        "rcph9"
      ]
    },
    {
      "value": "pam",
      "label": "Music Division",
      "holdingLocations": [
        "pam11",
        "pam22",
        "pam32",
        "pam38",
        "pam42",
        "pam48",
        "rcpm2",
        "rcpm8",
        "rcpm9"
      ]
    },
    {
      "value": "pat",
      "label": "Theatre Division",
      "holdingLocations": [
        "pat11",
        "pat22",
        "pat28",
        "pat32",
        "pat38",
        "pat42",
        "pat48",
        "rcpt2",
        "rcpt8",
        "rcpt9"
      ]
    },
    {
      "value": "pav",
      "label": "Reserve Film and Video",
      "holdingLocations": [
        "pav22",
        "pav28",
        "pav32",
        "pav38",
        "rcpr2",
        "rcpr8",
        "rcpr9"
      ]
    },
    {
      "value": "scb",
      "label": "Moving Image and Recorded Sound Division",
      "holdingLocations": [
        "scbb2",
        "rccb2",
        "rccb8",
        "rccb9"
      ]
    },
    {
      "value": "scc",
      "label": "Art and Artifacts Division",
      "holdingLocations": [
        "sccc2",
        "sccc3",
        "rcca9"
      ]
    },
    {
      "value": "scd",
      "label": "Manuscripts, Archives and Rare Books Division",
      "holdingLocations": [
        "scdd1",
        "scdd2",
        "rccd2",
        "rccd8",
        "rccd9"
      ]
    },
    {
      "value": "sce",
      "label": "Photographs and Prints Division",
      "holdingLocations": [
        "scedd",
        "scee2",
        "rcce2",
        "rcce8",
        "rcce9"
      ]
    },
    {
      "value": "scf",
      "label": "Jean Blackwell Hutson Research and Reference Division",
      "holdingLocations": [
        "scff1",
        "scff2",
        "scff3",
        "rc2cf",
        "rc2cm",
        "rccf2",
        "rccf8",
        "rccf9"
      ]
    }
  ],
  "languages": [
    {
      "value": "lang:eng",
      "count": 8211656,
      "label": "English"
    },
    {
      "value": "lang:ger",
      "count": 1782321,
      "label": "German"
    },
    {
      "value": "lang:fre",
      "count": 1439569,
      "label": "French"
    },
    {
      "value": "lang:spa",
      "count": 1241128,
      "label": "Spanish"
    },
    {
      "value": "lang:ita",
      "count": 834397,
      "label": "Italian"
    },
    {
      "value": "lang:rus",
      "count": 718582,
      "label": "Russian"
    },
    {
      "value": "lang:ara",
      "count": 459691,
      "label": "Arabic"
    },
    {
      "value": "lang:chi",
      "count": 453873,
      "label": "Chinese"
    },
    {
      "value": "lang:por",
      "count": 289368,
      "label": "Portuguese"
    },
    {
      "value": "lang:jpn",
      "count": 288806,
      "label": "Japanese"
    },
    {
      "value": "lang:zxx",
      "count": 282914,
      "label": "No linguistic content"
    },
    {
      "value": "lang:heb",
      "count": 269650,
      "label": "Hebrew"
    },
    {
      "value": "lang:pol",
      "count": 208585,
      "label": "Polish"
    },
    {
      "value": "lang:dut",
      "count": 179633,
      "label": "Dutch"
    },
    {
      "value": "lang:kor",
      "count": 143845,
      "label": "Korean"
    },
    {
      "value": "lang:tur",
      "count": 132800,
      "label": "Turkish"
    },
    {
      "value": "lang:per",
      "count": 108133,
      "label": "Persian"
    },
    {
      "value": "lang:",
      "count": 97727,
      "label": ""
    },
    {
      "value": "lang:swe",
      "count": 94195,
      "label": "Swedish"
    },
    {
      "value": "lang:ukr",
      "count": 93981,
      "label": "Ukrainian"
    },
    {
      "value": "lang:lat",
      "count": 87222,
      "label": "Latin"
    },
    {
      "value": "lang:cze",
      "count": 78068,
      "label": "Czech"
    },
    {
      "value": "lang:gre",
      "count": 74787,
      "label": "Greek, Modern (1453- )"
    },
    {
      "value": "lang:dan",
      "count": 63988,
      "label": "Danish"
    },
    {
      "value": "lang:hun",
      "count": 58049,
      "label": "Hungarian"
    },
    {
      "value": "lang:hin",
      "count": 51465,
      "label": "Hindi"
    },
    {
      "value": "lang:bul",
      "count": 46622,
      "label": "Bulgarian"
    },
    {
      "value": "lang:cat",
      "count": 43852,
      "label": "Catalan"
    },
    {
      "value": "lang:urd",
      "count": 41718,
      "label": "Urdu"
    },
    {
      "value": "lang:rum",
      "count": 39753,
      "label": "Romanian"
    },
    {
      "value": "lang:nor",
      "count": 39261,
      "label": "Norwegian"
    },
    {
      "value": "lang:fin",
      "count": 36604,
      "label": "Finnish"
    },
    {
      "value": "lang:hrv",
      "count": 35786,
      "label": "Croatian"
    },
    {
      "value": "lang:srp",
      "count": 32912,
      "label": "Serbian"
    },
    {
      "value": "lang:und",
      "count": 30933,
      "label": "Undetermined"
    },
    {
      "value": "lang:ben",
      "count": 27343,
      "label": "Bengali"
    },
    {
      "value": "lang:yid",
      "count": 24602,
      "label": "Yiddish"
    },
    {
      "value": "lang:arm",
      "count": 24328,
      "label": "Armenian"
    },
    {
      "value": "lang:tam",
      "count": 23872,
      "label": "Tamil"
    },
    {
      "value": "lang:mul",
      "count": 23137,
      "label": "Multiple languages"
    },
    {
      "value": "lang:lav",
      "count": 18471,
      "label": "Latvian"
    },
    {
      "value": "lang:slo",
      "count": 18241,
      "label": "Slovak"
    },
    {
      "value": "lang:san",
      "count": 16417,
      "label": "Sanskrit"
    },
    {
      "value": "lang:tib",
      "count": 15422,
      "label": "Tibetan"
    },
    {
      "value": "lang:ind",
      "count": 14543,
      "label": "Indonesian"
    },
    {
      "value": "lang:bel",
      "count": 13723,
      "label": "Belarusian"
    },
    {
      "value": "lang:lit",
      "count": 11249,
      "label": "Lithuanian"
    },
    {
      "value": "lang:slv",
      "count": 11071,
      "label": "Slovenian"
    },
    {
      "value": "lang:geo",
      "count": 10941,
      "label": "Georgian"
    },
    {
      "value": "lang:est",
      "count": 10410,
      "label": "Estonian"
    },
    {
      "value": "lang:uzb",
      "count": 9417,
      "label": "Uzbek"
    },
    {
      "value": "lang:aze",
      "count": 9283,
      "label": "Azerbaijani"
    },
    {
      "value": "lang:mac",
      "count": 8964,
      "label": "Macedonian"
    },
    {
      "value": "lang:pan",
      "count": 8835,
      "label": "Panjabi"
    },
    {
      "value": "lang:ice",
      "count": 8617,
      "label": "Icelandic"
    },
    {
      "value": "lang:alb",
      "count": 8323,
      "label": "Albanian"
    },
    {
      "value": "lang:afr",
      "count": 8311,
      "label": "Afrikaans"
    },
    {
      "value": "lang:kaz",
      "count": 7569,
      "label": "Kazakh"
    },
    {
      "value": "lang:ota",
      "count": 7357,
      "label": "Turkish, Ottoman"
    },
    {
      "value": "lang:nep",
      "count": 7007,
      "label": "Nepali"
    },
    {
      "value": "lang:kur",
      "count": 6942,
      "label": "Kurdish"
    },
    {
      "value": "lang:vie",
      "count": 6439,
      "label": "Vietnamese"
    },
    {
      "value": "lang:glg",
      "count": 5953,
      "label": "Galician"
    },
    {
      "value": "lang:mal",
      "count": 5806,
      "label": "Malayalam"
    },
    {
      "value": "lang:tel",
      "count": 5788,
      "label": "Telugu"
    },
    {
      "value": "lang:wel",
      "count": 5682,
      "label": "Welsh"
    },
    {
      "value": "lang:kan",
      "count": 5382,
      "label": "Kannada"
    },
    {
      "value": "lang:bos",
      "count": 5315,
      "label": "Bosnian"
    },
    {
      "value": "lang:gle",
      "count": 5192,
      "label": "Irish"
    },
    {
      "value": "lang:snd",
      "count": 4919,
      "label": "Sindhi"
    },
    {
      "value": "lang:grc",
      "count": 4845,
      "label": "Greek, Ancient (to 1453)"
    },
    {
      "value": "lang:kir",
      "count": 4228,
      "label": "Kyrgyz"
    },
    {
      "value": "lang:swa",
      "count": 3916,
      "label": "Swahili"
    },
    {
      "value": "lang:pus",
      "count": 3617,
      "label": "Pushto"
    },
    {
      "value": "lang:ori",
      "count": 3587,
      "label": "Oriya"
    },
    {
      "value": "lang:tat",
      "count": 3335,
      "label": "Tatar"
    },
    {
      "value": "lang:mon",
      "count": 3183,
      "label": "Mongolian"
    },
    {
      "value": "lang:guj",
      "count": 3054,
      "label": "Gujarati"
    },
    {
      "value": "lang:epo",
      "count": 2793,
      "label": "Esperanto"
    },
    {
      "value": "lang:may",
      "count": 2781,
      "label": "Malay"
    },
    {
      "value": "lang:mar",
      "count": 2734,
      "label": "Marathi"
    },
    {
      "value": "lang:uig",
      "count": 2713,
      "label": "Uighur"
    },
    {
      "value": "lang:tgk",
      "count": 2666,
      "label": "Tajik"
    },
    {
      "value": "lang:amh",
      "count": 2433,
      "label": "Amharic"
    },
    {
      "value": "lang:asm",
      "count": 2416,
      "label": "Assamese"
    },
    {
      "value": "lang:scr",
      "count": 2388,
      "label": ""
    },
    {
      "value": "lang:bak",
      "count": 2369,
      "label": "Bashkir"
    },
    {
      "value": "lang:tuk",
      "count": 2111,
      "label": "Turkmen"
    },
    {
      "value": "lang:tut",
      "count": 2013,
      "label": "Altaic (Other)"
    },
    {
      "value": "lang:chv",
      "count": 1986,
      "label": "Chuvash"
    },
    {
      "value": "lang:baq",
      "count": 1831,
      "label": "Basque"
    },
    {
      "value": "lang:tha",
      "count": 1787,
      "label": "Thai"
    },
    {
      "value": "lang:scc",
      "count": 1565,
      "label": ""
    },
    {
      "value": "lang:sin",
      "count": 1458,
      "label": "Sinhalese"
    },
    {
      "value": "lang:nob",
      "count": 1384,
      "label": "Norwegian (Bokmål)"
    },
    {
      "value": "lang:fiu",
      "count": 1244,
      "label": "Finno-Ugrian (Other)"
    },
    {
      "value": "lang:yor",
      "count": 1227,
      "label": "Yoruba"
    },
    {
      "value": "lang:N/A",
      "count": 1225,
      "label": ""
    },
    {
      "value": "lang:cau",
      "count": 1214,
      "label": "Caucasian (Other)"
    },
    {
      "value": "lang:chu",
      "count": 1160,
      "label": "Church Slavic"
    },
    {
      "value": "lang:oci",
      "count": 1079,
      "label": "Occitan (post-1500)"
    },
    {
      "value": "lang:raj",
      "count": 1055,
      "label": "Rajasthani"
    },
    {
      "value": "lang:nic",
      "count": 1053,
      "label": "Niger-Kordofanian (Other)"
    },
    {
      "value": "lang:fry",
      "count": 1051,
      "label": "Frisian"
    },
    {
      "value": "lang:bur",
      "count": 1024,
      "label": "Burmese"
    },
    {
      "value": "lang:mlt",
      "count": 995,
      "label": "Maltese"
    },
    {
      "value": "lang:myn",
      "count": 920,
      "label": "Mayan languages"
    },
    {
      "value": "lang:wen",
      "count": 907,
      "label": "Sorbian (Other)"
    },
    {
      "value": "lang:bre",
      "count": 851,
      "label": "Breton"
    },
    {
      "value": "lang:new",
      "count": 819,
      "label": "Newari"
    },
    {
      "value": "lang:roa",
      "count": 800,
      "label": "Romance (Other)"
    },
    {
      "value": "lang:mlg",
      "count": 788,
      "label": "Malagasy"
    },
    {
      "value": "lang:cpf",
      "count": 753,
      "label": "Creoles and Pidgins, French-based (Other)"
    },
    {
      "value": "lang:bal",
      "count": 745,
      "label": "Baluchi"
    },
    {
      "value": "lang:pra",
      "count": 735,
      "label": "Prakrit languages"
    },
    {
      "value": "lang:sna",
      "count": 728,
      "label": "Shona"
    },
    {
      "value": "lang:fro",
      "count": 721,
      "label": "French, Old (ca. 842-1300)"
    },
    {
      "value": "lang:fao",
      "count": 686,
      "label": "Faroese"
    },
    {
      "value": "lang:gem",
      "count": 680,
      "label": "Germanic (Other)"
    },
    {
      "value": "lang:roh",
      "count": 679,
      "label": "Raeto-Romance"
    },
    {
      "value": "lang:hau",
      "count": 640,
      "label": "Hausa"
    },
    {
      "value": "lang:frm",
      "count": 625,
      "label": "French, Middle (ca. 1300-1600)"
    },
    {
      "value": "lang:map",
      "count": 607,
      "label": "Austronesian (Other)"
    },
    {
      "value": "lang:gmh",
      "count": 582,
      "label": "German, Middle High (ca. 1050-1500)"
    },
    {
      "value": "lang:som",
      "count": 580,
      "label": "Somali"
    },
    {
      "value": "lang:pli",
      "count": 577,
      "label": "Pali"
    },
    {
      "value": "lang:lad",
      "count": 566,
      "label": "Ladino"
    },
    {
      "value": "lang:enm",
      "count": 564,
      "label": "English, Middle (1100-1500)"
    },
    {
      "value": "lang:bnt",
      "count": 559,
      "label": "Bantu (Other)"
    },
    {
      "value": "lang:gla",
      "count": 557,
      "label": "Scottish Gaelic"
    },
    {
      "value": "lang:oss",
      "count": 551,
      "label": "Ossetic"
    },
    {
      "value": "lang:syr",
      "count": 528,
      "label": "Syriac, Modern"
    },
    {
      "value": "lang:ber",
      "count": 514,
      "label": "Berber (Other)"
    },
    {
      "value": "lang:mai",
      "count": 512,
      "label": "Maithili"
    },
    {
      "value": "lang:inc",
      "count": 501,
      "label": "Indic (Other)"
    },
    {
      "value": "lang:chm",
      "count": 498,
      "label": "Mari"
    },
    {
      "value": "lang:pro",
      "count": 497,
      "label": "Provençal (to 1500)"
    },
    {
      "value": "lang:sai",
      "count": 469,
      "label": "South American Indian (Other)"
    },
    {
      "value": "lang:dra",
      "count": 456,
      "label": "Dravidian (Other)"
    },
    {
      "value": "lang:tir",
      "count": 455,
      "label": "Tigrinya"
    },
    {
      "value": "lang:sah",
      "count": 453,
      "label": "Yakut"
    },
    {
      "value": "lang:sot",
      "count": 444,
      "label": "Sotho"
    },
    {
      "value": "lang:hat",
      "count": 442,
      "label": "Haitian French Creole"
    },
    {
      "value": "lang:tgl",
      "count": 442,
      "label": "Tagalog"
    },
    {
      "value": "lang:rom",
      "count": 418,
      "label": "Romani"
    },
    {
      "value": "lang:lus",
      "count": 403,
      "label": "Lushai"
    },
    {
      "value": "lang:egy",
      "count": 398,
      "label": "Egyptian"
    },
    {
      "value": "lang:lug",
      "count": 391,
      "label": "Ganda"
    },
    {
      "value": "lang:paa",
      "count": 387,
      "label": "Papuan (Other)"
    },
    {
      "value": "lang:xho",
      "count": 383,
      "label": "Xhosa"
    },
    {
      "value": "lang:udm",
      "count": 379,
      "label": "Udmurt"
    },
    {
      "value": "lang:tsn",
      "count": 378,
      "label": "Tswana"
    },
    {
      "value": "lang:zul",
      "count": 351,
      "label": "Zulu"
    },
    {
      "value": "lang:kin",
      "count": 346,
      "label": "Kinyarwanda"
    },
    {
      "value": "lang:ful",
      "count": 321,
      "label": "Fula"
    },
    {
      "value": "lang:kaa",
      "count": 318,
      "label": "Kara-Kalpak"
    },
    {
      "value": "lang:nde",
      "count": 314,
      "label": "Ndebele (Zimbabwe)"
    },
    {
      "value": "lang:kom",
      "count": 302,
      "label": "Komi"
    },
    {
      "value": "lang:doi",
      "count": 301,
      "label": "Dogri"
    },
    {
      "value": "lang:nya",
      "count": 301,
      "label": "Nyanja"
    },
    {
      "value": "lang:sla",
      "count": 299,
      "label": "Slavic (Other)"
    },
    {
      "value": "lang:wol",
      "count": 292,
      "label": "Wolof"
    },
    {
      "value": "lang:bho",
      "count": 290,
      "label": "Bhojpuri"
    },
    {
      "value": "lang:orm",
      "count": 289,
      "label": "Oromo"
    },
    {
      "value": "lang:bra",
      "count": 282,
      "label": "Braj"
    },
    {
      "value": "lang:che",
      "count": 280,
      "label": "Chechen"
    },
    {
      "value": "lang:que",
      "count": 264,
      "label": "Quechua"
    },
    {
      "value": "lang:sit",
      "count": 264,
      "label": "Sino-Tibetan (Other)"
    },
    {
      "value": "lang:lah",
      "count": 263,
      "label": "Lahndā"
    },
    {
      "value": "lang:ang",
      "count": 255,
      "label": "English, Old (ca. 450-1100)"
    },
    {
      "value": "lang:cai",
      "count": 255,
      "label": "Central American Indian (Other)"
    },
    {
      "value": "lang:jrb",
      "count": 236,
      "label": "Judeo-Arabic"
    },
    {
      "value": "lang:kha",
      "count": 232,
      "label": "Khasi"
    },
    {
      "value": "lang:crp",
      "count": 228,
      "label": "Creoles and Pidgins (Other)"
    },
    {
      "value": "lang:grn",
      "count": 226,
      "label": "Guarani"
    },
    {
      "value": "lang:nno",
      "count": 224,
      "label": "Norwegian (Nynorsk)"
    },
    {
      "value": "lang:twi",
      "count": 218,
      "label": "Twi"
    },
    {
      "value": "lang:ibo",
      "count": 212,
      "label": "Igbo"
    },
    {
      "value": "lang:jav",
      "count": 210,
      "label": "Javanese"
    },
    {
      "value": "lang:kas",
      "count": 202,
      "label": "Kashmiri"
    },
    {
      "value": "lang:arc",
      "count": 188,
      "label": "Aramaic"
    },
    {
      "value": "lang:mol",
      "count": 185,
      "label": ""
    },
    {
      "value": "lang:man",
      "count": 183,
      "label": "Mandingo"
    },
    {
      "value": "lang:haw",
      "count": 181,
      "label": "Hawaiian"
    },
    {
      "value": "lang:ssa",
      "count": 172,
      "label": "Nilo-Saharan (Other)"
    },
    {
      "value": "lang:phi",
      "count": 161,
      "label": "Philippine (Other)"
    },
    {
      "value": "lang:ava",
      "count": 156,
      "label": "Avaric"
    },
    {
      "value": "lang:bam",
      "count": 151,
      "label": "Bambara"
    },
    {
      "value": "lang:nah",
      "count": 151,
      "label": "Nahuatl"
    },
    {
      "value": "lang:afa",
      "count": 147,
      "label": "Afroasiatic (Other)"
    },
    {
      "value": "lang:nai",
      "count": 145,
      "label": "North American Indian (Other)"
    },
    {
      "value": "lang:nso",
      "count": 143,
      "label": "Northern Sotho"
    },
    {
      "value": "lang:cop",
      "count": 140,
      "label": "Coptic"
    },
    {
      "value": "lang:ady",
      "count": 138,
      "label": "Adygei"
    },
    {
      "value": "lang:zza",
      "count": 138,
      "label": "Zaza"
    },
    {
      "value": "lang:kal",
      "count": 134,
      "label": "Kalâtdlisut"
    },
    {
      "value": "lang:kbd",
      "count": 134,
      "label": "Kabardian"
    },
    {
      "value": "lang:pap",
      "count": 132,
      "label": "Papiamento"
    },
    {
      "value": "lang:ewe",
      "count": 130,
      "label": "Ewe"
    },
    {
      "value": "lang:mis",
      "count": 130,
      "label": "Miscellaneous languages"
    },
    {
      "value": "lang:kon",
      "count": 124,
      "label": "Kongo"
    },
    {
      "value": "lang:cre",
      "count": 121,
      "label": "Cree"
    },
    {
      "value": "lang:sco",
      "count": 118,
      "label": "Scots"
    },
    {
      "value": "lang:oji",
      "count": 116,
      "label": "Ojibwa"
    },
    {
      "value": "lang:khm",
      "count": 115,
      "label": "Khmer"
    },
    {
      "value": "lang:ndo",
      "count": 111,
      "label": "Ndonga"
    },
    {
      "value": "lang:gez",
      "count": 109,
      "label": "Ethiopic"
    },
    {
      "value": "lang:cpp",
      "count": 108,
      "label": "Creoles and Pidgins, Portuguese-based (Other)"
    },
    {
      "value": "lang:dzo",
      "count": 108,
      "label": "Dzongkha"
    },
    {
      "value": "lang:mao",
      "count": 105,
      "label": "Maori"
    },
    {
      "value": "lang:kab",
      "count": 103,
      "label": "Kabyle"
    },
    {
      "value": "lang:awa",
      "count": 101,
      "label": "Awadhi"
    },
    {
      "value": "lang:gaa",
      "count": 101,
      "label": "Gã"
    },
    {
      "value": "lang:smi",
      "count": 100,
      "label": "Sami"
    },
    {
      "value": "lang:mni",
      "count": 99,
      "label": "Manipuri"
    },
    {
      "value": "lang:ssw",
      "count": 99,
      "label": "Swazi"
    },
    {
      "value": "lang:ira",
      "count": 97,
      "label": "Iranian (Other)"
    },
    {
      "value": "lang:tso",
      "count": 96,
      "label": "Tsonga"
    },
    {
      "value": "lang:ast",
      "count": 95,
      "label": "Bable"
    },
    {
      "value": "lang:mus",
      "count": 95,
      "label": "Creek"
    },
    {
      "value": "lang:bua",
      "count": 94,
      "label": "Buriat"
    },
    {
      "value": "lang:dak",
      "count": 93,
      "label": "Dakota"
    },
    {
      "value": "lang:mno",
      "count": 93,
      "label": "Manobo languages"
    },
    {
      "value": "lang:kik",
      "count": 90,
      "label": "Kikuyu"
    },
    {
      "value": "lang:bem",
      "count": 89,
      "label": "Bemba"
    },
    {
      "value": "lang:cho",
      "count": 88,
      "label": "Choctaw"
    },
    {
      "value": "lang:ypk",
      "count": 88,
      "label": "Yupik languages"
    },
    {
      "value": "lang:lao",
      "count": 86,
      "label": "Lao"
    },
    {
      "value": "lang:cnr",
      "count": 85,
      "label": ""
    },
    {
      "value": "lang:cpe",
      "count": 83,
      "label": "Creoles and Pidgins, English-based (Other)"
    },
    {
      "value": "lang:akk",
      "count": 82,
      "label": "Akkadian"
    },
    {
      "value": "lang:chg",
      "count": 80,
      "label": "Chagatai"
    },
    {
      "value": "lang:mos",
      "count": 80,
      "label": "Mooré"
    },
    {
      "value": "lang:myv",
      "count": 80,
      "label": "Erzya"
    },
    {
      "value": "lang:dum",
      "count": 79,
      "label": "Dutch, Middle (ca. 1050-1350)"
    },
    {
      "value": "lang:srd",
      "count": 77,
      "label": "Sardinian"
    },
    {
      "value": "lang:sun",
      "count": 76,
      "label": "Sundanese"
    },
    {
      "value": "lang:aym",
      "count": 75,
      "label": "Aymara"
    },
    {
      "value": "lang:pal",
      "count": 75,
      "label": "Pahlavi"
    },
    {
      "value": "lang:zap",
      "count": 73,
      "label": "Zapotec"
    },
    {
      "value": "lang:snk",
      "count": 72,
      "label": "Soninke"
    },
    {
      "value": "lang:run",
      "count": 68,
      "label": "Rundi"
    },
    {
      "value": "lang:abk",
      "count": 67,
      "label": "Abkhaz"
    },
    {
      "value": "lang:alg",
      "count": 66,
      "label": "Algonquian (Other)"
    },
    {
      "value": "lang:kua",
      "count": 66,
      "label": "Kuanyama"
    },
    {
      "value": "lang:chr",
      "count": 65,
      "label": "Cherokee"
    },
    {
      "value": "lang:him",
      "count": 64,
      "label": "Western Pahari languages"
    },
    {
      "value": "lang:gag",
      "count": 63,
      "label": ""
    },
    {
      "value": "lang:mdf",
      "count": 63,
      "label": "Moksha"
    },
    {
      "value": "lang:xal",
      "count": 63,
      "label": "Oirat"
    },
    {
      "value": "lang:fur",
      "count": 62,
      "label": "Friulian"
    },
    {
      "value": "lang:srr",
      "count": 61,
      "label": "Serer"
    },
    {
      "value": "lang:kum",
      "count": 59,
      "label": "Kumyk"
    },
    {
      "value": "lang:crh",
      "count": 58,
      "label": "Crimean Tatar"
    },
    {
      "value": "lang:syc",
      "count": 57,
      "label": "Syriac"
    },
    {
      "value": "lang:nds",
      "count": 56,
      "label": "Low German"
    },
    {
      "value": "lang:khi",
      "count": 55,
      "label": "Khoisan (Other)"
    },
    {
      "value": "lang:loz",
      "count": 55,
      "label": "Lozi"
    },
    {
      "value": "lang:got",
      "count": 54,
      "label": "Gothic"
    },
    {
      "value": "lang:lin",
      "count": 54,
      "label": "Lingala"
    },
    {
      "value": "lang:inh",
      "count": 53,
      "label": "Ingush"
    },
    {
      "value": "lang:her",
      "count": 52,
      "label": "Herero"
    },
    {
      "value": "lang:mwr",
      "count": 52,
      "label": "Marwari"
    },
    {
      "value": "lang:tyv",
      "count": 52,
      "label": "Tuvinian"
    },
    {
      "value": "lang:ban",
      "count": 51,
      "label": "Balinese"
    },
    {
      "value": "lang:nap",
      "count": 51,
      "label": "Neapolitan Italian"
    },
    {
      "value": "lang:ven",
      "count": 51,
      "label": "Venda"
    },
    {
      "value": "lang:kar",
      "count": 50,
      "label": "Karen languages"
    },
    {
      "value": "lang:moh",
      "count": 50,
      "label": "Mohawk"
    },
    {
      "value": "lang:dyu",
      "count": 49,
      "label": "Dyula"
    },
    {
      "value": "lang:fat",
      "count": 49,
      "label": "Fanti"
    },
    {
      "value": "lang:son",
      "count": 49,
      "label": "Songhai"
    },
    {
      "value": "lang:shn",
      "count": 48,
      "label": "Shan"
    },
    {
      "value": "lang:iku",
      "count": 47,
      "label": "Inuktitut"
    },
    {
      "value": "lang:luo",
      "count": 47,
      "label": "Luo (Kenya and Tanzania)"
    },
    {
      "value": "lang:nyn",
      "count": 47,
      "label": "Nyankole"
    },
    {
      "value": "lang:goh",
      "count": 45,
      "label": "German, Old High (ca. 750-1050)"
    },
    {
      "value": "lang:ina",
      "count": 45,
      "label": "Interlingua (International Auxiliary Language Association)"
    },
    {
      "value": "lang:iri",
      "count": 45,
      "label": ""
    },
    {
      "value": "lang:kro",
      "count": 45,
      "label": "Kru (Other)"
    },
    {
      "value": "lang:krc",
      "count": 42,
      "label": "Karachay-Balkar"
    },
    {
      "value": "lang:mnc",
      "count": 42,
      "label": "Manchu"
    },
    {
      "value": "lang:smo",
      "count": 42,
      "label": "Samoan"
    },
    {
      "value": "lang:arn",
      "count": 41,
      "label": "Mapuche"
    },
    {
      "value": "lang:krl",
      "count": 41,
      "label": "Karelian"
    },
    {
      "value": "lang:nav",
      "count": 41,
      "label": "Navajo"
    },
    {
      "value": "lang:ltz",
      "count": 40,
      "label": "Luxembourgish"
    },
    {
      "value": "lang:sam",
      "count": 38,
      "label": "Samaritan Aramaic"
    },
    {
      "value": "lang:tah",
      "count": 38,
      "label": "Tahitian"
    },
    {
      "value": "lang:efi",
      "count": 37,
      "label": "Efik"
    },
    {
      "value": "lang:iro",
      "count": 37,
      "label": "Iroquoian (Other)"
    },
    {
      "value": "lang:lez",
      "count": 37,
      "label": "Lezgian"
    },
    {
      "value": "lang:mun",
      "count": 37,
      "label": "Munda (Other)"
    },
    {
      "value": "lang:oto",
      "count": 37,
      "label": "Otomian languages"
    },
    {
      "value": "lang:aka",
      "count": 36,
      "label": "Akan"
    },
    {
      "value": "lang:art",
      "count": 36,
      "label": "Artificial (Other)"
    },
    {
      "value": "lang:cos",
      "count": 36,
      "label": "Corsican"
    },
    {
      "value": "lang:cel",
      "count": 35,
      "label": "Celtic (Other)"
    },
    {
      "value": "lang:cor",
      "count": 35,
      "label": "Cornish"
    },
    {
      "value": "lang:gsw",
      "count": 35,
      "label": "Swiss German"
    },
    {
      "value": "lang:men",
      "count": 35,
      "label": "Mende"
    },
    {
      "value": "lang:arg",
      "count": 34,
      "label": "Aragonese"
    },
    {
      "value": "lang:kok",
      "count": 34,
      "label": "Konkani"
    },
    {
      "value": "lang:non",
      "count": 33,
      "label": "Old Norse"
    },
    {
      "value": "lang:sme",
      "count": 33,
      "label": "Northern Sami"
    },
    {
      "value": "lang:ceb",
      "count": 32,
      "label": "Cebuano"
    },
    {
      "value": "lang:lol",
      "count": 32,
      "label": "Mongo-Nkundu"
    },
    {
      "value": "lang:sux",
      "count": 32,
      "label": "Sumerian"
    },
    {
      "value": "lang:bas",
      "count": 31,
      "label": "Basa"
    },
    {
      "value": "lang:dar",
      "count": 30,
      "label": "Dargwa"
    },
    {
      "value": "lang:ilo",
      "count": 30,
      "label": "Iloko"
    },
    {
      "value": "lang:lan",
      "count": 30,
      "label": ""
    },
    {
      "value": "lang:nzi",
      "count": 30,
      "label": "Nzima"
    },
    {
      "value": "lang:tmh",
      "count": 30,
      "label": "Tamashek"
    },
    {
      "value": "lang:gae",
      "count": 29,
      "label": ""
    },
    {
      "value": "lang:kam",
      "count": 29,
      "label": "Kamba"
    },
    {
      "value": "lang:jpr",
      "count": 28,
      "label": "Judeo-Persian"
    },
    {
      "value": "lang:glv",
      "count": 27,
      "label": "Manx"
    },
    {
      "value": "lang:tog",
      "count": 27,
      "label": "Tonga (Nyasa)"
    },
    {
      "value": "lang:alt",
      "count": 26,
      "label": "Altai"
    },
    {
      "value": "lang:mag",
      "count": 26,
      "label": "Magahi"
    },
    {
      "value": "lang:scn",
      "count": 25,
      "label": "Sicilian Italian"
    },
    {
      "value": "lang:tar",
      "count": 25,
      "label": ""
    },
    {
      "value": "lang:tum",
      "count": 25,
      "label": "Tumbuka"
    },
    {
      "value": "lang:ijo",
      "count": 24,
      "label": "Ijo"
    },
    {
      "value": "lang:tig",
      "count": 24,
      "label": "Tigré"
    },
    {
      "value": "lang:bih",
      "count": 23,
      "label": "Bihari (Other)"
    },
    {
      "value": "lang:grb",
      "count": 23,
      "label": "Grebo"
    },
    {
      "value": "lang:pon",
      "count": 23,
      "label": "Pohnpeian"
    },
    {
      "value": "lang:",
      "count": 23,
      "label": "t"
    },
    {
      "value": "lang:ada",
      "count": 22,
      "label": "Adangme"
    },
    {
      "value": "lang:csb",
      "count": 22,
      "label": "Kashubian"
    },
    {
      "value": "lang:ido",
      "count": 22,
      "label": "Ido"
    },
    {
      "value": "lang:nyo",
      "count": 22,
      "label": "Nyoro"
    },
    {
      "value": "lang:ath",
      "count": 21,
      "label": "Athapascan (Other)"
    },
    {
      "value": "lang:ave",
      "count": 21,
      "label": "Avestan"
    },
    {
      "value": "lang:kru",
      "count": 20,
      "label": "Kurukh"
    },
    {
      "value": "lang:lub",
      "count": 20,
      "label": "Luba-Katanga"
    },
    {
      "value": "lang:fan",
      "count": 19,
      "label": "Fang"
    },
    {
      "value": "lang:fon",
      "count": 19,
      "label": "Fon"
    },
    {
      "value": "lang:hil",
      "count": 19,
      "label": "Hiligaynon"
    },
    {
      "value": "lang:sal",
      "count": 19,
      "label": "Salishan languages"
    },
    {
      "value": "lang:N A",
      "count": 18,
      "label": ""
    },
    {
      "value": "lang:ach",
      "count": 18,
      "label": "Acoli"
    },
    {
      "value": "lang:hsb",
      "count": 18,
      "label": "Upper Sorbian"
    },
    {
      "value": "lang:nub",
      "count": 18,
      "label": "Nubian languages"
    },
    {
      "value": "lang:tem",
      "count": 18,
      "label": "Temne"
    },
    {
      "value": "lang:kaw",
      "count": 17,
      "label": "Kawi"
    },
    {
      "value": "lang:pam",
      "count": 17,
      "label": "Pampanga"
    },
    {
      "value": "lang:dua",
      "count": 16,
      "label": "Duala"
    },
    {
      "value": "lang:esp",
      "count": 16,
      "label": ""
    },
    {
      "value": "lang:fri",
      "count": 16,
      "label": ""
    },
    {
      "value": "lang:gil",
      "count": 16,
      "label": "Gilbertese"
    },
    {
      "value": "lang:pag",
      "count": 16,
      "label": "Pangasinan"
    },
    {
      "value": "lang:uga",
      "count": 16,
      "label": "Ugaritic"
    },
    {
      "value": "lang:cus",
      "count": 15,
      "label": "Cushitic (Other)"
    },
    {
      "value": "lang:den",
      "count": 15,
      "label": "Slavey"
    },
    {
      "value": "lang:eka",
      "count": 15,
      "label": "Ekajuk"
    },
    {
      "value": "lang:tai",
      "count": 15,
      "label": "Tai (Other)"
    },
    {
      "value": "lang:taj",
      "count": 15,
      "label": ""
    },
    {
      "value": "lang:wln",
      "count": 15,
      "label": "Walloon"
    },
    {
      "value": "lang:bai",
      "count": 14,
      "label": "Bamileke languages"
    },
    {
      "value": "lang:del",
      "count": 14,
      "label": "Delaware"
    },
    {
      "value": "lang:nbl",
      "count": 14,
      "label": "Ndebele (South Africa)"
    },
    {
      "value": "lang:nog",
      "count": 14,
      "label": "Nogai"
    },
    {
      "value": "lang:aar",
      "count": 13,
      "label": "Afar"
    },
    {
      "value": "lang:arw",
      "count": 13,
      "label": "Arawak"
    },
    {
      "value": "lang:iba",
      "count": 13,
      "label": "Iban"
    },
    {
      "value": "lang:min",
      "count": 13,
      "label": "Minangkabau"
    },
    {
      "value": "lang:mkh",
      "count": 13,
      "label": "Mon-Khmer (Other)"
    },
    {
      "value": "lang:apa",
      "count": 12,
      "label": "Apache languages"
    },
    {
      "value": "lang:esk",
      "count": 12,
      "label": ""
    },
    {
      "value": "lang:mah",
      "count": 12,
      "label": "Marshallese"
    },
    {
      "value": "lang:pau",
      "count": 12,
      "label": "Palauan"
    },
    {
      "value": "lang:ton",
      "count": 12,
      "label": "Tongan"
    },
    {
      "value": "lang:vol",
      "count": 12,
      "label": "Volapük"
    },
    {
      "value": "lang:btk",
      "count": 11,
      "label": "Batak"
    },
    {
      "value": "lang:ewo",
      "count": 11,
      "label": "Ewondo"
    },
    {
      "value": "lang:fij",
      "count": 11,
      "label": "Fijian"
    },
    {
      "value": "lang:ine",
      "count": 11,
      "label": "Indo-European (Other)"
    },
    {
      "value": "lang:mic",
      "count": 11,
      "label": "Micmac"
    },
    {
      "value": "lang:yao",
      "count": 11,
      "label": "Yao (Africa)"
    },
    {
      "value": "lang:bat",
      "count": 10,
      "label": "Baltic (Other)"
    },
    {
      "value": "lang:din",
      "count": 10,
      "label": "Dinka"
    },
    {
      "value": "lang:lua",
      "count": 10,
      "label": "Luba-Lulua"
    },
    {
      "value": "lang:mas",
      "count": 10,
      "label": "Maasai"
    },
    {
      "value": "lang:sem",
      "count": 10,
      "label": "Semitic (Other)"
    },
    {
      "value": "lang:sio",
      "count": 10,
      "label": "Siouan (Other)"
    },
    {
      "value": "lang:aus",
      "count": 9,
      "label": "Australian languages"
    },
    {
      "value": "lang:bla",
      "count": 9,
      "label": "Siksika"
    },
    {
      "value": "lang:car",
      "count": 9,
      "label": "Carib"
    },
    {
      "value": "lang:chy",
      "count": 9,
      "label": "Cheyenne"
    },
    {
      "value": "lang:kmb",
      "count": 9,
      "label": "Kimbundu"
    },
    {
      "value": "lang:kos",
      "count": 9,
      "label": "Kosraean"
    },
    {
      "value": "lang:sad",
      "count": 9,
      "label": "Sandawe"
    },
    {
      "value": "lang:sag",
      "count": 9,
      "label": "Sango (Ubangi Creole)"
    },
    {
      "value": "lang:ace",
      "count": 8,
      "label": "Achinese"
    },
    {
      "value": "lang:bik",
      "count": 8,
      "label": "Bikol"
    },
    {
      "value": "lang:bug",
      "count": 8,
      "label": "Bugis"
    },
    {
      "value": "lang:chn",
      "count": 8,
      "label": "Chinook jargon"
    },
    {
      "value": "lang:eth",
      "count": 8,
      "label": ""
    },
    {
      "value": "lang:fil",
      "count": 8,
      "label": "Filipino"
    },
    {
      "value": "lang:hmn",
      "count": 8,
      "label": "Hmong"
    },
    {
      "value": "lang:ile",
      "count": 8,
      "label": "Interlingue"
    },
    {
      "value": "lang:kpe",
      "count": 8,
      "label": "Kpelle"
    },
    {
      "value": "lang:mak",
      "count": 8,
      "label": "Makasar"
    },
    {
      "value": "lang:sat",
      "count": 8,
      "label": "Santali"
    },
    {
      "value": "lang:tet",
      "count": 8,
      "label": "Tetum"
    },
    {
      "value": "lang:tiv",
      "count": 8,
      "label": "Tiv"
    },
    {
      "value": "lang:vai",
      "count": 8,
      "label": "Vai"
    },
    {
      "value": "lang:wal",
      "count": 8,
      "label": "Wolayta"
    },
    {
      "value": "lang:zun",
      "count": 8,
      "label": "Zuni"
    },
    {
      "value": "lang:cha",
      "count": 7,
      "label": "Chamorro"
    },
    {
      "value": "lang:day",
      "count": 7,
      "label": "Dayak"
    },
    {
      "value": "lang:elx",
      "count": 7,
      "label": "Elamite"
    },
    {
      "value": "lang:frr",
      "count": 7,
      "label": "North Frisian"
    },
    {
      "value": "lang:gal",
      "count": 7,
      "label": ""
    },
    {
      "value": "lang:gon",
      "count": 7,
      "label": "Gondi"
    },
    {
      "value": "lang:kau",
      "count": 7,
      "label": "Kanuri"
    },
    {
      "value": "lang:tag",
      "count": 7,
      "label": ""
    },
    {
      "value": "lang:a d",
      "count": 6,
      "label": ""
    },
    {
      "value": "lang:ale",
      "count": 6,
      "label": "Aleut"
    },
    {
      "value": "lang:bis",
      "count": 6,
      "label": "Bislama"
    },
    {
      "value": "lang:chk",
      "count": 6,
      "label": "Chuukese"
    },
    {
      "value": "lang:gay",
      "count": 6,
      "label": "Gayo"
    },
    {
      "value": "lang:kac",
      "count": 6,
      "label": "Kachin"
    },
    {
      "value": "lang:lun",
      "count": 6,
      "label": "Lunda"
    },
    {
      "value": "lang:sel",
      "count": 6,
      "label": "Selkup"
    },
    {
      "value": "lang:tli",
      "count": 6,
      "label": "Tlingit"
    },
    {
      "value": "lang:umb",
      "count": 6,
      "label": "Umbundu"
    },
    {
      "value": "lang:bin",
      "count": 5,
      "label": "Edo"
    },
    {
      "value": "lang:far",
      "count": 5,
      "label": ""
    },
    {
      "value": "lang:hai",
      "count": 5,
      "label": "Haida"
    },
    {
      "value": "lang:lam",
      "count": 5,
      "label": "Lamba (Zambia and Congo)"
    },
    {
      "value": "lang:mad",
      "count": 5,
      "label": "Madurese"
    },
    {
      "value": "lang:mga",
      "count": 5,
      "label": "Irish, Middle (ca. 1100-1550)"
    },
    {
      "value": "lang:mwl",
      "count": 5,
      "label": "Mirandese"
    },
    {
      "value": "lang:rup",
      "count": 5,
      "label": "Aromanian"
    },
    {
      "value": "lang:sho",
      "count": 5,
      "label": ""
    },
    {
      "value": "lang:sus",
      "count": 5,
      "label": "Susu"
    },
    {
      "value": "lang:tsi",
      "count": 5,
      "label": "Tsimshian"
    },
    {
      "value": "lang:_ru",
      "count": 4,
      "label": ""
    },
    {
      "value": "lang:anp",
      "count": 4,
      "label": "Angika"
    },
    {
      "value": "lang:cmc",
      "count": 4,
      "label": "Chamic languages"
    },
    {
      "value": "lang:fra",
      "count": 4,
      "label": ""
    },
    {
      "value": "lang:ipk",
      "count": 4,
      "label": "Inupiaq"
    },
    {
      "value": "lang:rar",
      "count": 4,
      "label": "Rarotongan"
    },
    {
      "value": "lang:sga",
      "count": 4,
      "label": "Irish, Old (to 1100)"
    },
    {
      "value": "lang:sid",
      "count": 4,
      "label": "Sidamo"
    },
    {
      "value": "lang:smj",
      "count": 4,
      "label": "Lule Sami"
    },
    {
      "value": "lang:snh",
      "count": 4,
      "label": ""
    },
    {
      "value": "lang:sog",
      "count": 4,
      "label": "Sogdian"
    },
    {
      "value": "lang:ter",
      "count": 4,
      "label": "Terena"
    },
    {
      "value": "lang:tup",
      "count": 4,
      "label": "Tupi languages"
    },
    {
      "value": "lang:vot",
      "count": 4,
      "label": "Votic"
    },
    {
      "value": "lang:wak",
      "count": 4,
      "label": "Wakashan languages"
    },
    {
      "value": "lang:war",
      "count": 4,
      "label": "Waray"
    },
    {
      "value": "lang:ain",
      "count": 3,
      "label": "Ainu"
    },
    {
      "value": "lang:byn",
      "count": 3,
      "label": "Bilin"
    },
    {
      "value": "lang:dsb",
      "count": 3,
      "label": "Lower Sorbian"
    },
    {
      "value": "lang:engfreger",
      "count": 3,
      "label": ""
    },
    {
      "value": "lang:engger",
      "count": 3,
      "label": ""
    },
    {
      "value": "lang:enk",
      "count": 3,
      "label": ""
    },
    {
      "value": "lang:gba",
      "count": 3,
      "label": "Gbaya"
    },
    {
      "value": "lang:gua",
      "count": 3,
      "label": ""
    },
    {
      "value": "lang:hit",
      "count": 3,
      "label": "Hittite"
    },
    {
      "value": "lang:peo",
      "count": 3,
      "label": "Old Persian (ca. 600-400 B.C.)"
    },
    {
      "value": "lang:sao",
      "count": 3,
      "label": ""
    },
    {
      "value": "lang:sma",
      "count": 3,
      "label": "Southern Sami"
    },
    {
      "value": "lang:srn",
      "count": 3,
      "label": "Sranan"
    },
    {
      "value": "lang:tsw",
      "count": 3,
      "label": ""
    },
    {
      "value": "lang:|sp",
      "count": 3,
      "label": ""
    },
    {
      "value": "lang:bej",
      "count": 2,
      "label": "Beja"
    },
    {
      "value": "lang:bru",
      "count": 2,
      "label": ""
    },
    {
      "value": "lang:cad",
      "count": 2,
      "label": "Caddo"
    },
    {
      "value": "lang:cam",
      "count": 2,
      "label": ""
    },
    {
      "value": "lang:chb",
      "count": 2,
      "label": "Chibcha"
    },
    {
      "value": "lang:deu",
      "count": 2,
      "label": ""
    },
    {
      "value": "lang:dru",
      "count": 2,
      "label": ""
    },
    {
      "value": "lang:engfre",
      "count": 2,
      "label": ""
    },
    {
      "value": "lang:frs",
      "count": 2,
      "label": "East Frisian"
    },
    {
      "value": "lang:g c",
      "count": 2,
      "label": ""
    },
    {
      "value": "lang:gmhger",
      "count": 2,
      "label": ""
    },
    {
      "value": "lang:int",
      "count": 2,
      "label": ""
    },
    {
      "value": "lang:max",
      "count": 2,
      "label": ""
    },
    {
      "value": "lang:nau",
      "count": 2,
      "label": "Nauru"
    },
    {
      "value": "lang:nqo",
      "count": 2,
      "label": "N'Ko"
    },
    {
      "value": "lang:osa",
      "count": 2,
      "label": "Osage"
    },
    {
      "value": "lang:pa",
      "count": 2,
      "label": "|"
    },
    {
      "value": "lang:rap",
      "count": 2,
      "label": "Rapanui"
    },
    {
      "value": "lang:sas",
      "count": 2,
      "label": "Sasak"
    },
    {
      "value": "lang:sms",
      "count": 2,
      "label": "Skolt Sami"
    },
    {
      "value": "lang:suk",
      "count": 2,
      "label": "Sukuma"
    },
    {
      "value": "lang:zha",
      "count": 2,
      "label": "Zhuang"
    },
    {
      "value": "lang:znd",
      "count": 2,
      "label": "Zande languages"
    },
    {
      "value": "lang:0 f",
      "count": 1,
      "label": ""
    },
    {
      "value": "lang:0a0",
      "count": 1,
      "label": ""
    },
    {
      "value": "lang:0re",
      "count": 1,
      "label": ""
    },
    {
      "value": "lang:0tu",
      "count": 1,
      "label": ""
    },
    {
      "value": "lang:???",
      "count": 1,
      "label": ""
    }
  ],
  "buildingLocations": [
    {
      "value": "ma",
      "label": "Stephen A. Schwarzman Building (SASB)",
      "nickname": "SASB"
    },
    {
      "value": "pa",
      "label": "The New York Public Library for the Performing Arts (LPA)",
      "nickname": "LPA"
    },
    {
      "value": "sc",
      "label": "Schomburg Center for Research in Black Culture",
      "nickname": "Schomburg"
    },
    {
      "value": "rc",
      "label": "Offsite - request in advance"
    },
    {
      "value": "bu",
      "label": "Stavros Niarchos Foundation Library (SNFL)",
      "nickname": "SNFL"
    }
  ]
};
    