import fs from "fs"
import path from "path"

const loadSearchVocabs = async (): Promise<void> => {
  try {
    const response = await fetch(
      "http://localhost:8080/research/research-catalog/api/vocabularies"
    )
    if (!response.ok) {
      throw new Error(`Failed to fetch vocabularies: ${response.statusText}`)
    }
    const data = await response.json()
    const filePath = path.join(process.cwd(), "data", "searchVocabularies.ts")
    const fileContent = `// generated by loadSearchVocabs()
    export const searchVocabularies = ${JSON.stringify(data, null, 2)};
    `
    fs.writeFileSync(filePath, fileContent)

    console.log("Successfully wrote to data/searchVocabularies.ts")
  } catch (error) {
    console.error("Error loading search vocabs:", error)
    process.exit(1)
  }
}

loadSearchVocabs()
