# Deploys to research-catalog-qa
name: deploy qa

on:
  push:
    branches:
      - qa
      - SCC-4218/move-rc-from-travis-to-github-actions

permissions:
  id-token: write
  contents: read

env:
  AWS_DEFAULT_REGION: us-east-1
  LOCAL_TAG_NAME: research-catalog:${{ github.ref_name }}-${{ github.run_number }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::946183545209:role/GithubActionsDeployerRole
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image to Amazon ECR
        env:
          NEXT_PUBLIC_APP_ENV: qa
          ECR_URL: 946183545209.dkr.ecr.us-east-1.amazonaws.com/research-catalog:$NEXT_PUBLIC_APP_ENV-latest
        run: |
          docker build --build-arg NEXT_PUBLIC_APP_ENV=$NEXT_PUBLIC_APP_ENV --tag $LOCAL_TAG_NAME .
          docker tag $LOCAL_TAG_NAME $ECR_URL
          # docker push $ECR_URL

      # - name: Update ECS service
      #   run: |
      #     aws ecs update-service --cluster research-catalog-qa --service research-catalog-qa --force-new-deployment
